# Dependabot are scheduled to avoid contention with normal workday CI usage. We
# start running updates at 3AM UTC (7PM PST, 8AM IST) and stagger each
# subsequent update by 30m.
version: 2
updates:
  - package-ecosystem: cargo
    directory: "/"
    schedule:
      interval: daily
      time: "03:30"
      timezone: "UTC"
    allow:
      - dependency-type: "all"
    ignore:
      # These dependencies will be updated via higher-level aggregator dependencies like `clap`,
      # `futures`, `kube`, `prost`, and `tracing`:
      - dependency-name: "clap_derive"
      - dependency-name: "futures-channel"
      - dependency-name: "futures-core"
      - dependency-name: "futures-io"
      - dependency-name: "futures-sink"
      - dependency-name: "futures-task"
      - dependency-name: "futures-util"
      - dependency-name: "kube"
      - dependency-name: "kube-client"
      - dependency-name: "kube-core"
      - dependency-name: "kube-derive"
      - dependency-name: "kube-runtime"
      - dependency-name: "prost-derive"
      - dependency-name: "tracing-attributes"
      - dependency-name: "tracing-core"
      - dependency-name: "tracing-serde"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
      time: "04:00"
      timezone: "UTC"
