targets = [
    { triple = "x86_64-unknown-linux-gnu" },
    { triple = "aarch64-unknown-linux-gnu" },
    { triple = "armv7-unknown-linux-gnu" },
]

[advisories]
db-path = "~/.cargo/advisory-db"
db-urls = ["https://github.com/rustsec/advisory-db"]
vulnerability = "deny"
unmaintained = "warn"
yanked = "deny"
notice = "warn"
ignore = [
    # https://github.com/kube-rs/kube-rs/issues/650
    # https://github.com/kube-rs/kube-rs/issues/660
    "RUSTSEC-2020-0159",
]

[licenses]
unlicensed = "deny"
allow = ["Apache-2.0", "BSD-3-Clause", "MIT"]
deny = []
copyleft = "deny"
allow-osi-fsf-free = "neither"
default = "deny"
confidence-threshold = 0.8
exceptions = []

[bans]
multiple-versions = "deny"
wildcards = "deny"
highlight = "all"
deny = []
skip-tree = []
skip = [
    # Waiting on kube v0.70
    { name = "parking_lot", version = "0.11" },
    { name = "parking_lot_core", version = "0.8" },
    { name = "tokio-util", version = "0.6" },
]

[sources]
unknown-registry = "deny"
unknown-git = "deny"
allow-registry = ["https://github.com/rust-lang/crates.io-index"]
allow-git = []
