apiVersion: apps/v1
kind: Deployment
metadata:
  name: podinfo-central
spec:
  replicas: {{.Values.podinfoCentral.replicas }}
  selector:
    matchLabels:
      location: central
  template:
    metadata:
      labels:
        location: central
    spec:
      containers:
      - name: podinfo
        image: ghcr.io/stefanprodan/podinfo:6.0.3
        env:
        - name: PODINFO_UI_MESSAGE
          value: "central"
        ports:
        - name: http
          containerPort: 9898
          protocol: TCP
