apiVersion: split.smi-spec.io/v1alpha2
kind: TrafficSplit
metadata:
  name: podinfo-ts
  annotations:
    failover.linkerd.io/primary-service: podinfo-west
  labels:
    failover.linkerd.io/controlled-by: linkerd-failover
spec:
  service: podinfo
  backends:
  - service: podinfo-west
    weight: 1
  - service: podinfo-central
    weight: 0
  - service: podinfo-east
    weight: 0
