apiVersion: batch/v1
kind: Job
metadata:
  annotations:
    "helm.sh/hook": post-install
    "helm.sh/hook-weight": "0"
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
  labels:
    app.kubernetes.io/name: namespace-metadata
    app.kubernetes.io/part-of: linkerd-failover
    app.kubernetes.io/version: {{.Values.image.tag}}
  name: namespace-metadata
spec:
  template:
    metadata:
      labels:
        app.kubernetes.io/name: namespace-metadata
        app.kubernetes.io/part-of: linkerd-failover
        app.kubernetes.io/version: {{.Values.image.tag}}
    spec:
      restartPolicy: Never
      serviceAccountName: namespace-metadata
      containers:
      - name: namespace-metadata
        image: {{.Values.namespaceMetadata.image.registry}}/{{.Values.namespaceMetadata.image.name}}:{{.Values.namespaceMetadata.image.tag}}
        imagePullPolicy: {{.Values.namespaceMetadata.image.pullPolicy }}
        args:
        - --log-format
        - {{.Values.logFormat}}
        - --log-level
        - {{.Values.logLevel}}
        - --extension
        - failover
        - --namespace
        - {{.Release.Namespace}}
        - --linkerd-namespace
        - {{.Values.linkerdNamespace}}
